Ctrl<Key>w         : NextWord()
Ctrl<Key>a         : BackTab()
Ctrl<Key>e         : FieldEnd()
Ctrl<Key>p         : Up()
Ctrl<Key>n         : Down()
Ctrl<Key>b         : Left()
Ctrl<Key>f         : Right()
Ctrl<Key>d         : Delete()
Ctrl<Key>x         : Disconnect()
Ctrl<Key>l <Key>p  : Home()
Ctrl<Key>l <Key>i  : ToggleInsert()
Ctrl<Key>l <Key>w  : PreviousWord()
Ctrl<Key>l <Key>p  : Scroll(Backward)
Ctrl<Key>l <Key>n  : Scroll(Forward)
